name: fetch_tray_hooks
description: Provides flutter_hooks support to fetch_tray
version: 0.0.1
homepage: https://github.com/marqably/fetch_tray_hooks
repository: https://github.com/marqably/fetch_tray_hooks
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_hooks: ^0.20.4
  fetch_tray:
    git:
      url: https://github.com/Lightgaming/fetch_tray.git
      ref: 65714e488654c9563051354e0b6c88812bde2b42

  hooks_riverpod: ^2.3.6
  dio: ^5.2.1+1
  mockito: ^5.4.2

dev_dependencies:
  test:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.5

flutter:
